# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-16 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_address_item_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='line_two',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
