# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0003_auto_20170516_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Property.Address'),
        ),
    ]
