# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0004_auto_20170517_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='room_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Property.Room'),
        ),
        migrations.AddField(
            model_name='room',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Property.Unit'),
        ),
    ]
