# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0003_auto_20170516_0457'),
        ('Person', '0001_initial'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Property.Address')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='item',
            field=models.ManyToManyField(null=True, to='Property.Item'),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.ManyToManyField(null=True, to='Person.Owner'),
        ),
        migrations.AddField(
            model_name='task',
            name='staff',
            field=models.ManyToManyField(null=True, to='Person.Staff'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('D', 'Drywall'), ('E', 'Electrical'), ('P', 'Painting'), ('PG', 'Plumbing'), ('PL', 'Plaster'), ('R', 'Replacement'), ('A', 'Appliance')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tenant',
            field=models.ManyToManyField(null=True, to='Person.Tenant'),
        ),
        migrations.AddField(
            model_name='task',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Person.Vendor'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='room',
        ),
        migrations.AddField(
            model_name='task',
            name='room',
            field=models.ManyToManyField(null=True, to='Property.Room'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='task_items',
            field=models.ManyToManyField(to='Order.Task'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Property.Unit'),
        ),
        migrations.AddField(
            model_name='task',
            name='review',
            field=models.ManyToManyField(null=True, to='Order.Review'),
        ),
    ]
