# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_remove_workorder_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='tenant',
        ),
        migrations.AlterField(
            model_name='task',
            name='item',
            field=models.ManyToManyField(blank=True, null=True, to='Property.Item'),
        ),
        migrations.AlterField(
            model_name='task',
            name='room',
            field=models.ManyToManyField(blank=True, null=True, to='Property.Room'),
        ),
    ]
