# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_auto_20170518_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='task_items',
        ),
        migrations.AddField(
            model_name='task',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.WorkOrder'),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
