# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0006_auto_20170518_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='staff',
        ),
        migrations.AddField(
            model_name='task',
            name='date_assigned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='date_scheduled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='item',
            field=models.ManyToManyField(blank=True, to='Property.Item'),
        ),
        migrations.AlterField(
            model_name='task',
            name='review',
            field=models.ManyToManyField(blank=True, to='Order.Review'),
        ),
        migrations.AlterField(
            model_name='task',
            name='room',
            field=models.ManyToManyField(blank=True, to='Property.Room'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('D', 'Drywall'), ('E', 'Electrical'), ('P', 'Painting'), ('PG', 'Plumbing'), ('PL', 'Plaster'), ('R', 'Replacement'), ('A', 'Appliance'), ('T', 'Trash Removal'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='staff',
            field=models.ManyToManyField(to='Person.Staff'),
        ),
    ]
