# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0007_auto_20170522_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='stage',
            field=models.CharField(choices=[('C', 'Created'), ('G', 'Getting Quote'), ('A', 'Assigned Vendor'), ('S', 'Scheduled'), ('N', 'Needs Reviews'), ('D', 'Done')], default='C', max_length=1),
        ),
    ]
